spring:
  application:
    name: bilibili-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 7002
  servlet:
    context-path: /
  shutdown:  graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: log/${spring.application.name}/${POD_NAME:local_dev}

baidu:
  trans:
    app-id: ${BAIDU_TRANS_APP_ID}
    key: ${BAIDU_TRANS_KEY}

minio:
  endpoint: ${MINIO_ENDPOINT}
  credentials:
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}

bili-up:
  # noinspection SpellCheckingInspection
  path: ${BILI_UP_PATH:biliup}
  concurrent:
    thread: ${BILI_UP_CONCURRENT_THREAD:5}
  # noinspection SpellCheckingInspection
  tag: ${BILI_UP_TAG:综艺}
  title-prefix: ${BILI_UP_TITLE_PREFIX:[生肉] }