replicaCount: 1

image:
  repository: wecgwm/bilibili-service
  pullPolicy: Always
  tag: "master"

podLabels:
  metrics: enable

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

server:
  port: 7002
  contextPath: /

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: BILIBILI_LOG_LEVEL
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILIBILI_LOG_LEVEL
  - name: MINIO_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_ENDPOINT
  - name: MINIO_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_ACCESS_KEY
  - name: MINIO_SECRET_KEY
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_SECRET_KEY
  - name: BAIDU_TRANS_APP_ID
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BAIDU_TRANS_APP_ID
  - name: BAIDU_TRANS_KEY
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BAIDU_TRANS_KEY
  - name: BILI_UP_PATH
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILI_UP_PATH
  - name: BILI_UP_CONCURRENT_THREAD
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILI_UP_CONCURRENT_THREAD
  - name: BILI_UP_TAG
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILI_UP_TAG
  - name: BILI_UP_TITLE_PREFIX
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILI_UP_TITLE_PREFIX
  - name: BILI_UP_LINE
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: BILI_UP_LINE

#envFrom:
#  - secretRef:
#      name:  java-secret


volumeMounts:
  - mountPath: /application/log
    name: log-volume
  - mountPath: /application/biliup
    name: biliup-rust
  - mountPath: /application/cookies.json
    name: biliup-rust-cookie

volumes:
  - name: log-volume
    hostPath:
      path: /usr/local/log
      type: Directory
  - name: biliup-rust
    hostPath:
      path: /usr/local/biliup-rust/biliup
      type: File
  - name: biliup-rust-cookie
    hostPath:
      path: /usr/local/biliup-rust/cookies.json
      type: File


resources:
  limits:
    cpu: 800m
    memory: 800Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 7002

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  http:
    - paths:
        - path: /bilibili-service
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - wecgwm.com
      secretName: tls-secret

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}